name: XcodeBuildCI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild clean build -scheme ResourcesSPM -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.3'
    - name: Run tests
      run: xcodebuild clean test -scheme ResourcesSPM -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.3'
